exports.sources = [
  {
    name: "Libération",
    realName: "Libération",
    url: "https://www.liberation.fr/idees-et-debats/editorial",
    articlesPath: "div.left-article-section div:nth-child(4) > div article",
    titleCss: "h2",
    urlArticleCss: "a",
    previewCss: "div.left-article-section > div > span",
    paragraphsCss: "article > p",
  },
  {
    name: "Boulevard Voltaire",
    realName: "Boulevard Voltaire",
    url: "https://www.bvoltaire.fr/rubrique/editoriaux/",
    articlesPath: "li.articles-box-item",
    titleCss: "h3",
    urlArticleCss: ".article-details a",
    previewCss: "",
    paragraphsCss: "div.pf-content p",
  },
  {
    name: "Blast",
    realName: "Blast",
    url: "https://www.blast-info.fr/tags/tribune-JZJGiJ6YTH62AA32cErgKA",
    articlesPath: ".story-list-item",
    titleCss: ".text-dark h2",
    urlArticleCss: "a.text-dark",
    previewCss: ".story-headline-text p",
    paragraphsCss: ".story-content p",
  },
  {
    name: "Est Républicain",
    realName: "L'Est Républicain",
    url: "https://www.estrepublicain.fr/actualite/edito",
    articlesPath: "article.richcontent",
    titleCss: "a h2",
    urlArticleCss: "a",
    previewCss: "",
    paragraphsCss: ".textComponent p",
  },
  {
    name: "La Croix",
    realName: "La Croix",
    url: "https://www.la-croix.com/Debats/Editos",
    articlesPath: "article.article-block",
    titleCss: "a h2",
    urlArticleCss: "a",
    previewCss: ".article-intro > p",
    paragraphsCss: ".ap-article-trigger > p",
  },
  {
    name: "La Tribune",
    realName: "La Tribune",
    url: "https://www.latribune.fr/opinions/editos/accueil-editos.html",
    articlesPath: ".article-wrapper",
    titleCss: "h2",
    urlArticleCss: "a",
    previewCss: "section.chapo",
    paragraphsCss: "#body-article > p",
    premiumCss: "span.protected",
  },
  {
    name: "Figaro",
    realName: "Le Figaro",
    url: "https://www.lefigaro.fr/vox",
    articlesPath: "article.fig-profile",
    titleCss: "h2",
    urlArticleCss: "a",
    previewCss: "p.fig-standfirst",
    paragraphsCss: "p.fig-paragraph",
    premiumCss: ".fig-premium-mark",
  },
  {
    name: "Monde",
    realName: "Le Monde",
    url: "https://www.lemonde.fr/editoriaux/",
    articlesPath: "div.thread",
    titleCss: "section a h3",
    urlArticleCss: "section a",
    previewCss: "p.article__desc",
    paragraphsCss: "p.article__paragraph",
  },
  {
    name: "L'Express",
    realName: "L'Express",
    url: "https://www.lexpress.fr/actualite/idees-et-debats/",
    articlesPath: "div.sous-home__une > article > div.thumbnail__text",
    titleCss: "h3",
    urlArticleCss: "h3 a",
    previewCss: ".article__lead",
    paragraphsCss: "p.article__item",
  },
  {
    name: "Humanite",
    realName: "L'Humanité",
    url: "https://www.humanite.fr/etiquettes/tribunes",
    articlesPath:
      "div.view-content > div.views-row > div > div.group-description",
    titleCss: "div.field-name-title > div > div > h2",
    urlArticleCss: "div.field-name-title > div > div > h2 a",
    previewCss:
      "div.field-name-field-news-chapo:nth-child(1) > div:nth-child(1) > div:nth-child(1) > p:nth-child(1)",
    paragraphsCss: "div.field-group-div div.field-item.even p",
  },
  {
    name: "Opinion",
    realName: "L'Opinion",
    url: "https://www.lopinion.fr/opinions",
    articlesPath: "ul.listing-articles li",
    titleCss: "a",
    urlArticleCss: "a",
    previewCss: ".article_surtitre p",
    paragraphsCss: "div.qiota_reserve p",
  },
  {
    name: "Marianne",
    realName: "Marianne",
    url: "https://www.marianne.net/agora",
    articlesPath:
      "li.agora__list-item > article > div:nth-child(2) > div:nth-child(2)",
    titleCss: "h4",
    urlArticleCss: "h4 a",
    previewCss: "h2.article__headline",
    paragraphsCss: "p.article-text",
    premiumCss: "h4 > svg",
  },
  {
    name: "le monde diplomatique",
    realName: "Le Monde Diplomatique",
    url: "https://blog.mondediplo.net/",
    articlesPath: "ul.liste li.item",
    titleCss: "a h3",
    urlArticleCss: "a",
    previewCss: "",
    paragraphsCss: "div.contenu-principal div.crayon p",
  },
  {
    name: "Obs",
    realName: "Nouvel Obs",
    url: "https://www.nouvelobs.com/editos-et-chroniques/",
    articlesPath: "div.two-thirds article",
    titleCss: "h2",
    urlArticleCss: "a",
    previewCss: "h2.article__abstract, .article-page__chapo",
    paragraphsCss: "main p, #ObsArticle-body p",
    premiumCss: "span",
  },
  {
    name: "Conversation",
    realName: "The Conversation",
    url: "https://theconversation.com/fr/politique",
    articlesPath: "div > div > article",
    titleCss: "header > div > h2",
    urlArticleCss: "figure > a",
    previewCss: "",
    paragraphsCss: ".content-body p",
  },
  {
    name: "Valeurs Actuelles",
    realName: "Valeurs Actuelles",
    url: "https://www.valeursactuelles.com/lincorrect",
    articlesPath: "main > section > div > div > article",
    titleCss: "div.card-post__content > h2",
    urlArticleCss: "div.card-post__content > h2 a",
    previewCss: ".post__excerpt",
    paragraphsCss: "div.qiota_reserve > p",
  },
  {
    name: "l'Incorrect",
    realName: "L'Incorrect",
    url: "https://lincorrect.org/opinion/",
    articlesPath: "div.jet-smart-tiles",
    titleCss: ".jet-smart-tiles__box-title",
    urlArticleCss: "div > a",
    previewCss: "",
    paragraphsCss: "span.jet-listing-dynamic-field__content > p",
  },
  {
    name: "Challenges",
    realName: "Challenges",
    url: "https://www.challenges.fr/search/edito/",
    articlesPath: ".list-img-txt .item",
    titleCss: "a h2",
    urlArticleCss: "a",
    previewCss: ".article-chapo",
    paragraphsCss: ".container .corps p",
  },
  {
    name: "France Soir",
    realName: "France Soir",
    url: "https://www.francesoir.fr/rubrique/opinions",
    articlesPath: ".views-row",
    titleCss: "a",
    urlArticleCss: "a",
    previewCss: "",
    paragraphsCss: ".field-item p",
  },
  {
    name: "Contrepoints",
    realName: "Contrepoints",
    url: "https://www.contrepoints.org/category/edito",
    articlesPath: "li article.PostIntro",
    titleCss: ".PostIntro-title",
    urlArticleCss: "a",
    previewCss: ".PostContent-lead p",
    paragraphsCss: ".PostContent-body p",
  },
  {
    name: "Echos",
    realName: "Les Échos",
    url: "https://www.lesechos.fr/idees-debats/cercle",
    articlesPath: "article",
    titleCss: "h3",
    urlArticleCss: "a",
    previewCss: "header p",
    paragraphsCss: ".post-paywall p",
    premiumCss: "h3 svg",
  },
  {
    name: "Mediapart",
    realName: "Mediapart",
    url: "https://blogs.mediapart.fr/",
    articlesPath: "main .accur8-desktop > div:nth-child(2) ul li",
    titleCss: "a.title",
    urlArticleCss: "a.title",
    previewCss: ".introduction",
    paragraphsCss: ".content-article p",
  },
  {
    name: "Acrimed",
    realName: "Acrimed",
    url: "https://www.acrimed.org/",
    articlesPath: "div.row:nth-child(3) > div",
    titleCss: "a",
    urlArticleCss: "a",
    previewCss: "",
    paragraphsCss: "#article_main p",
  },
  {
    name: "Arret sur images",
    realName: "Arrêt sur Images",
    url: "https://www.arretsurimages.net/chroniques",
    articlesPath: "div.article-text-teaser",
    titleCss: "h3.title",
    urlArticleCss: "a.image-link",
    previewCss: "",
    paragraphsCss: "div.article-body p",
  },
];
